### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by rmatsum836**
## Description
Fix CI builds that haven't been updated in awhile.

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - [ ] TODO 1

## Questions
- [ ] Question1

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by rmatsum836** [comment]
Appveyor builds seem to be failing because `utils` can't be found.

**Comment by rmatsum836** [comment]
Changed the `dist` from `trusty` to `xenial` for the linux 3.7 build on Travis and is now passing.

**Comment by mattwthompson** [comment]
So Travis is working but Appveyor is not?

**Comment by rmatsum836** [comment]
Right, the builds in AppVeyor aren't able to import `pairing.utils`

**Comment by mattwthompson** [comment]
I'm ok just dropping it; I'm confident we could fix it but I don't believe spending more than an hour or two hunting down the bug would be worth it. The most I'd personally try is updating the yml against whatever we have in another functional repo

**Comment by rmatsum836** [comment]
I'm okay with that as well.

**Comment by rmatsum836** [comment]
I don't think I have the permissions to drop AppVeyor.  Once that's done, we can remove the AppVeyor badge from the README

**Comment by rmatsum836** [comment]
Closing in favor of #19

**Pull request closed without merging**
