### PR TITLE
Update functions and update tests to reflect changes

### PR DESCRIPTION
**Pull request by rmatsum836**
This PR may be too big to efficiently edit, correct, and ultimately merge.
But this PR has the following:

- Update `_generate_indirect_connectivity` that uses numpy calls to improve computational time

- elimination of functions related to old `_generate_indirect_connectivity` such as `_check_validity` that was necessary to confirm accuracy of indirect matrices.

- Addition of functions to calculate matrices

- Tests have been updated/ or deleted to reflect changes in functions

TODO: A few more tests should probably added for new functions.

### CODE REVIEW

**Comment by rmatsum836** [comment]
Travis is failing but it seems to be more to do with the way the build is set up

**Comment by mattwthompson** [comment]
There wasn't an `mtools` in the anaconda cloud. I have uploaded it to my channel, but it may only work for the Mac build.

**Comment by rmatsum836** [comment]
These lines `pytest -v --cov=pairing pairing/tests/` and ` conda install --use-local pairing` are missing in the current `.yml`.  Idk if these are lines we need

**Comment by rmatsum836** [comment]
Nevermind it seems like Travis is still failing due to no `mtools`

**Comment by mattwthompson** [comment]
I managed to upload a Mac binary but it doesn't seem to be getting found. I also still need to upload a linux binary.

https://anaconda.org/mwt/mtools/files

**Comment by mattwthompson** [comment]
LGTM, I am messing around with conda a bit but ok merging because it works locally.

**Comment by mattwthompson** [comment]
I'm fine merging this if you think it's ready

**Comment by rmatsum836** [comment]
Would eventually like to get CI working properly, and would like to have statistics on what the current codecov is, but I'm ready to merge.

**Pull request merged**
